@startuml proccess-flow

left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->

agent controller #9ff4ba
agent view #a2d3f9
agent usecases #f3a099
agent gateways #9ff4ba
agent presentations #9ff4ba
agent viewModel #a2d3f9
agent driver #a2d3f9

view --> controller: イベントハンドリング
controller --> usecases: 処理振り分け
usecases --> gateways: データ処理を委譲
gateways --> driver
usecases -> presentations: データ処理結果を委譲
viewModel <-- presentations: viewModelを更新
view <-- viewModel
@enduml